# .goreleaser.yml
project_name: custom-log-marshaler
builds:
  - dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - id: archive
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: custom-log-marshaler
    tap:
      owner: solodynamo
      name: homebrew-tap
    homepage: https://github.com/solodynamo/custom-log-marshaler
    description: Attempt to R.I.P PII or unnecessary info in logs and reduce log ingestion costs in the process.
    commit_author:
      name: Ankit Singh
      email: reachout@githubprofileblog
    install: |
      bin.install "custom-log-marshaler"