# .goreleaser.yml
project_name: custom-log-marshaler
builds:
  - id: custom-log-marshaler
    main: ./main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - id: archive
    format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: solodynamo
      name: homebrew-tap
