# .goreleaser.yml
project_name: custom-log-marshaler
builds:
  - dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - id: archive
    format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: solodynamo
      name: homebrew-tap
