# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CustomLogMarshaler < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.3/custom-log-marshaler_1.0.3_darwin_amd64.tar.gz"
      sha256 "1d6ca4a4996dbff79c4fa904cff4fd282b8d9b4c6bf511e9dc8963679d033226"

      def install
        bin.install "custom-log-marshaler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.3/custom-log-marshaler_1.0.3_darwin_arm64.tar.gz"
      sha256 "9ee24c5b6839aa9973438c790cb5322b0b83c6030ec0e502d9b577936c2a9536"

      def install
        bin.install "custom-log-marshaler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.3/custom-log-marshaler_1.0.3_linux_arm64.tar.gz"
      sha256 "0e7ea3f9c213e097695cc1f1b3544d805b068a713a78aee6c4194c80313b2085"

      def install
        bin.install "custom-log-marshaler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/solodynamo/custom-log-marshaler/releases/download/v1.0.3/custom-log-marshaler_1.0.3_linux_amd64.tar.gz"
      sha256 "5650997e06ceddf2ab5fc8d99af7416afe26c3916d99e1e8cb61971c5ab0095b"

      def install
        bin.install "custom-log-marshaler"
      end
    end
  end
end
